version: '3'

networks:
  app-network:
    driver: bridge

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app/
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: yii2basic
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    networks:
      - app-network